name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 23 * * 1' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://feed.cnblogs.com/blog/u/719644/rss/"
          # 博客园的话：https://www.cnblogs.com/swx123/rss 在自己博客后面加上/rss，就会自动跳转了
          max_post_count: 5
          template: "$newline - $randomEmoji(💯,🔥,💫,🚀,🌮,🦧,🦍)[$title $date]($url) $newline - $description $newline"
          description_max_length: "150"
